sudo: required
services:
 - docker

before_install:
 - docker build -t prashantthakur036/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true prashantthakur036/react-test npm test

after_success:
 - docker build -t prashantthakur036/multi-client ./client
 - docker build -t prashantthakur036/multi-nginx ./nginx
 - docker build -t prashantthakur036/multi-server ./server
 - docker build -t prashantthakur036/multi-worker ./worker

 # Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #Take these images and push it to docker hub
 - docker push prashantthakur036/multi-client
 - docker push prashantthakur036/multi-nginx
 - docker push prashantthakur036/multi-server
 - docker push prashantthakur036/multi-worker
